project:
  type: website

website:
  title: "Influenzanet Results"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intakes.qmd
        text: Participants profile
      - href: weekly.qmd
        text: Weekly data
      - href: central_db.qmd
        text: Central db (indivual data)
      - href: externals.qmd
        text: Externals
    footer:
        - href: about.qmd
          text: About us

format:
  html:
    theme: cosmo
#    css: styles.css
    toc: true
