---
title: "Data Quality"
format: 
  html:
    df-print: kable
---

This page show various inputs about Data in the analysis database

```{r include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE)
library(dplyr)
source("conf.R")

start_date = monday_of_date(Sys.Date()) - 3 * 7
season = get_current_season()

rows = NULL

for(survey in c('intake', 'weekly', 'vaccination')) {
  r = survey_load_results(survey, cols=c("timestamp", "country"), date = list(min=start_date), season=season)
  r$id = NULL
  r = r |> arrange(timestamp) |> mutate(yw=iso_yearweek(timestamp))
  r$yw = iso_yearweek(r$timestamp)
  
  rr = r %>% group_by(yw, country) %>% summarize(n=n(), participants=n_distinct(person_id), .groups = "drop")
  rr$survey = survey
  rows = bind_rows(rows, rr)
}

rows = rows |> arrange(yw, country) |> mutate(label=paste0(n, " (", participants, ")"))

```

```{r}

rr = tidyr::pivot_wider(rows |> select(country, survey, yw, label), id_cols=c('country', 'survey'), names_from = yw, values_from = label)

rr

```
