---
title: "externals"
format: 
  html:
    df-print: kable
---

```{r include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE)
library(RSQLite)
library(DBI)
library(dplyr)
source("conf.R")

init.path("ecdc")

db = DBI::dbConnect(RSQLite::SQLite(), external_db_path())

imports = dbGetQuery(db, "select * from imports")

# Only keeps last 5 imports for each country
imports = imports |> arrange(desc(imported_at)) %>% group_by(country) %>% slice_head(n=5) 

```


# Email receptions and file processed

```{r, echo=FALSE, message=FALSE, warning=FALSE}

emails_db_path = local_data_path("imports-email.db")
emails.db = DBI::dbConnect(RSQLite::SQLite(), emails_db_path)

emails = dbGetQuery(emails.db, "select * from email_imports")

emails = emails |> arrange(desc(time)) |> group_by(dir) |> slice_head(n=5)

kable_grouped = function(k, data) {
  gr = group_rows(data)
  gg = group_data(data)
  for(g in seq_along(gr)) {
    rows = gr[[g]]
    group_label = gg[g, ] |> select(-.rows)
    group_label = paste(group_label, collapse = " / ")
    k = k |> kableExtra::pack_rows(group_label=group_label, start_row=min(rows), end_row = max(rows))
  }
  k
}

d = emails |> select(time,  file, dir, msg_time, target_file)
kableExtra::kbl(d) |> kable_grouped(d)
```

# Import from externals sources

Only 5 last imports for each platform is shown. From April 2025, filenames are renamed to a common pattern.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
imports

```