DROP INDEX IF EXISTS idx_intake_q3_country;
DROP TABLE IF EXISTS epidb_results_intake CASCADE;
DROP TABLE IF EXISTS epidb_results_weekly CASCADE;

-- Relax Q4d_* to accept NULL
-- Relax Q17_* constraint to accept NULL
CREATE TABLE epidb_results_intake
(
  country character(2),
  global_id character varying(36),
  "timestamp" timestamp with time zone,
  "user" integer,
  "Q0" integer,
  "NOTE" text,
  "Q1" integer,
  "Q2" character varying(7),
  "Q3" character varying(30),
  "Q4" integer,
  "Q4b" integer,
  "Q4b_0_open" character varying(30),
  "Q4c" integer,
  "Q4d_0" boolean,
  "Q4d_1" boolean,
  "Q4d_2" boolean,
  "Q4d_3" boolean,
  "Q4d_4" boolean,
  "Q4d_5" boolean,
  "Q5_0" boolean NOT NULL,
  "Q5_1" boolean NOT NULL,
  "Q5_2" boolean NOT NULL,
  "Q5_3" boolean NOT NULL,
  "Q5_4" boolean NOT NULL,
  "Q6_0" boolean NOT NULL,
  "Q6_0_open" integer,
  "Q6_1" boolean NOT NULL,
  "Q6_1_open" integer,
  "Q6_2" boolean NOT NULL,
  "Q6_2_open" integer,
  "Q6_3" boolean NOT NULL,
  "Q6_3_open" integer,
  "Q6_4" boolean NOT NULL,
  "Q6_4_open" integer,
  "Q6b" integer,
  "Q7" integer,
  "Q7b" integer,
  "Q8" integer,
  "Q9" integer,
  "Q10" integer,
  "Q10b" integer,
  "Q10b_1_open" date,
  "Q10c_0" boolean NOT NULL,
  "Q10c_1" boolean NOT NULL,
  "Q10c_2" boolean NOT NULL,
  "Q10c_3" boolean NOT NULL,
  "Q10c_4" boolean NOT NULL,
  "Q10c_5" boolean NOT NULL,
  "Q10c_6" boolean NOT NULL,
  "Q10c_7" boolean NOT NULL,
  "Q10c_8" boolean NOT NULL,
  "Q10c_9" boolean NOT NULL,
  "Q10d_0" boolean NOT NULL,
  "Q10d_1" boolean NOT NULL,
  "Q10d_2" boolean NOT NULL,
  "Q10d_3" boolean NOT NULL,
  "Q10d_4" boolean NOT NULL,
  "Q10d_5" boolean NOT NULL,
  "Q10d_6" boolean NOT NULL,
  "Q10d_7" boolean NOT NULL,
  "Q10d_8" boolean NOT NULL,
  "Q10d_9" boolean NOT NULL,
  "Q10d_10" boolean NOT NULL,
  "Q10d_11" boolean NOT NULL,
  "Q10d_12" boolean NOT NULL,
  "Q10d_13" boolean NOT NULL,
  "Q10d_14" boolean NOT NULL,
  "Q11_0" boolean NOT NULL,
  "Q11_1" boolean NOT NULL,
  "Q11_2" boolean NOT NULL,
  "Q11_3" boolean NOT NULL,
  "Q11_4" boolean NOT NULL,
  "Q11_5" boolean NOT NULL,
  "Q11_6" boolean NOT NULL,
  "Q12" integer,
  "Q12b" integer,
  "Q13" integer,
  "Q14_1" boolean NOT NULL,
  "Q14_2" boolean NOT NULL,
  "Q14_3" boolean NOT NULL,
  "Q14_4" boolean NOT NULL,
  "Q14_5" boolean NOT NULL,
  "Q15_0" boolean,
  "Q15_1" boolean,
  "Q15_2" boolean,
  "Q15_3" boolean,
  "Q15_4" boolean,
  "Q16_0" boolean NOT NULL,
  "Q16_1" boolean NOT NULL,
  "Q16_2" boolean NOT NULL,
  "Q16_3" boolean NOT NULL,
  "Q16_4" boolean NOT NULL,
  "Q17_0" boolean,
  "Q17_1" boolean,
  "Q17_2" boolean,
  "Q17_3" boolean,
  "Q17_4" boolean,
  "Q17_5" boolean,
  CONSTRAINT "pollster_results_intake_Q0_check6" CHECK ("Q0" >= 0),
  CONSTRAINT "pollster_results_intake_Q10_check6" CHECK ("Q10" >= 0),
  CONSTRAINT "pollster_results_intake_Q10b_check6" CHECK ("Q10b" >= 0),
  CONSTRAINT "pollster_results_intake_Q12_check6" CHECK ("Q12" >= 0),
  CONSTRAINT "pollster_results_intake_Q12b_check6" CHECK ("Q12b" >= 0),
  CONSTRAINT "pollster_results_intake_Q13_check6" CHECK ("Q13" >= 0),
  CONSTRAINT "pollster_results_intake_Q1_check6" CHECK ("Q1" >= 0),
  CONSTRAINT "pollster_results_intake_Q4_check6" CHECK ("Q4" >= 0),
  CONSTRAINT "pollster_results_intake_Q4b_check6" CHECK ("Q4b" >= 0),
  CONSTRAINT "pollster_results_intake_Q4c_check6" CHECK ("Q4c" >= 0),
  CONSTRAINT "pollster_results_intake_Q6_0_open_check6" CHECK ("Q6_0_open" >= 0),
  CONSTRAINT "pollster_results_intake_Q6_1_open_check6" CHECK ("Q6_1_open" >= 0),
  CONSTRAINT "pollster_results_intake_Q6_2_open_check6" CHECK ("Q6_2_open" >= 0),
  CONSTRAINT "pollster_results_intake_Q6_3_open_check6" CHECK ("Q6_3_open" >= 0),
  CONSTRAINT "pollster_results_intake_Q6_4_open_check6" CHECK ("Q6_4_open" >= 0),
  CONSTRAINT "pollster_results_intake_Q6b_check6" CHECK ("Q6b" >= 0),
  CONSTRAINT "pollster_results_intake_Q7_check6" CHECK ("Q7" >= 0),
  CONSTRAINT "pollster_results_intake_Q7b_check6" CHECK ("Q7b" >= 0),
  CONSTRAINT "pollster_results_intake_Q8_check6" CHECK ("Q8" >= 0),
  CONSTRAINT "pollster_results_intake_Q9_check6" CHECK ("Q9" >= 0)
);

CREATE TABLE epidb_results_weekly
(
  country character(2),
  global_id character varying(36),
  "timestamp" timestamp with time zone,
  "Q1_0" boolean NOT NULL,
  "Q1_1" boolean NOT NULL,
  "Q1_2" boolean NOT NULL,
  "Q1_3" boolean NOT NULL,
  "Q1_4" boolean NOT NULL,
  "Q1_5" boolean NOT NULL,
  "Q1_6" boolean NOT NULL,
  "Q1_7" boolean NOT NULL,
  "Q1_8" boolean NOT NULL,
  "Q1_9" boolean NOT NULL,
  "Q1_10" boolean NOT NULL,
  "Q1_11" boolean NOT NULL,
  "Q1_12" boolean NOT NULL,
  "Q1_13" boolean NOT NULL,
  "Q1_14" boolean NOT NULL,
  "Q1_15" boolean NOT NULL,
  "Q1_16" boolean NOT NULL,
  "Q1_17" boolean NOT NULL,
  "Q1_18" boolean NOT NULL,
  "Q1_19" boolean NOT NULL,
  "Q2" integer,
  "N1" text,
  "Q3" integer,
  "Q3_0_open" date,
  "Q4" integer,
  "Q4_0_open" date,
  "Q5" integer,
  "Q6" integer,
  "Q6_1_open" date,
  "Q6b" integer,
  "Q6c" integer,
  "Q6d" integer,
  "Q7_0" boolean NOT NULL,
  "Q7_1" boolean NOT NULL,
  "Q7_3" boolean NOT NULL,
  "Q7_2" boolean NOT NULL,
  "Q7_4" boolean NOT NULL,
  "Q7_5" boolean NOT NULL,
  "Q7b_multi_row1_col1" integer,
  "Q7b_multi_row2_col1" integer,
  "Q7b_multi_row3_col1" integer,
  "Q7b_multi_row4_col1" integer,
  "Q8_0" boolean ,
  "Q8_1" boolean ,
  "Q8_2" boolean ,
  "Q8_3" boolean ,
  "Q8_4" boolean ,
  "Q8_5" boolean ,
  "Q8b_multi_row1_col1" integer,
  "Q8b_multi_row2_col1" integer,
  "Q8b_multi_row3_col1" integer,
  "Q8b_multi_row4_col1" integer,
  "Q9_0" boolean NOT NULL,
  "Q9_1" boolean NOT NULL,
  "Q9_2" boolean NOT NULL,
  "Q9_3" boolean NOT NULL,
  "Q9_4" boolean NOT NULL,
  "Q9_5" boolean NOT NULL,
  "Q9_6" boolean NOT NULL,
  "Q9b" integer,
  "Q10" integer,
  "Q10b" integer,
  "Q10c" integer,
  "Q11" integer,
  CONSTRAINT "pollster_results_weekly_Q10_check5" CHECK ("Q10" >= 0),
  CONSTRAINT "pollster_results_weekly_Q10b_check5" CHECK ("Q10b" >= 0),
  CONSTRAINT "pollster_results_weekly_Q10c_check5" CHECK ("Q10c" >= 0),
  CONSTRAINT "pollster_results_weekly_Q11_check5" CHECK ("Q11" >= 0),
  CONSTRAINT "pollster_results_weekly_Q2_check5" CHECK ("Q2" >= 0),
  CONSTRAINT "pollster_results_weekly_Q3_check5" CHECK ("Q3" >= 0),
  CONSTRAINT "pollster_results_weekly_Q4_check5" CHECK ("Q4" >= 0),
  CONSTRAINT "pollster_results_weekly_Q5_check5" CHECK ("Q5" >= 0),
  CONSTRAINT "pollster_results_weekly_Q6_check5" CHECK ("Q6" >= 0),
  CONSTRAINT "pollster_results_weekly_Q6b_check5" CHECK ("Q6b" >= 0),
  CONSTRAINT "pollster_results_weekly_Q6c_check5" CHECK ("Q6c" >= 0),
  CONSTRAINT "pollster_results_weekly_Q6d_check5" CHECK ("Q6d" >= 0),
  CONSTRAINT "pollster_results_weekly_Q7b_multi_row1_col1_check1" CHECK ("Q7b_multi_row1_col1" >= 0),
  CONSTRAINT "pollster_results_weekly_Q7b_multi_row2_col1_check1" CHECK ("Q7b_multi_row2_col1" >= 0),
  CONSTRAINT "pollster_results_weekly_Q7b_multi_row3_col1_check1" CHECK ("Q7b_multi_row3_col1" >= 0),
  CONSTRAINT "pollster_results_weekly_Q7b_multi_row4_col1_check1" CHECK ("Q7b_multi_row4_col1" >= 0),
  CONSTRAINT "pollster_results_weekly_Q8b_multi_row1_col1_check1" CHECK ("Q8b_multi_row1_col1" >= 0),
  CONSTRAINT "pollster_results_weekly_Q8b_multi_row2_col1_check1" CHECK ("Q8b_multi_row2_col1" >= 0),
  CONSTRAINT "pollster_results_weekly_Q8b_multi_row3_col1_check1" CHECK ("Q8b_multi_row3_col1" >= 0),
  CONSTRAINT "pollster_results_weekly_Q8b_multi_row4_col1_check1" CHECK ("Q8b_multi_row4_col1" >= 0),
  CONSTRAINT "pollster_results_weekly_Q9b_check5" CHECK ("Q9b" >= 0)
);
